/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_adas_MainActivity */

#ifndef _Included_com_example_adas_MainActivity
#define _Included_com_example_adas_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_adas_MainActivity_PERMISSION_REQUEST_CAMERA
#define com_example_adas_MainActivity_PERMISSION_REQUEST_CAMERA 0L
/*
 * Class:     com_example_adas_MainActivity
 * Method:    ProcessImage
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_example_adas_MainActivity_ProcessImage
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_adas_MainActivity
 * Method:    Initialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_adas_MainActivity_Initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_example_adas_MainActivity
 * Method:    Finalize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_adas_MainActivity_Finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
